// Generated by CoffeeScript 1.7.1
(function() {
  var Car;

  Car = (function() {
    function Car(configuration) {
      this.configuration = configuration;
    }

    Car.prototype.setBox2dData = function(box2dData) {
      this.b2Body = box2dData.carBody;
      this.rearTires = box2dData.rearTires;
      this.frontTires = box2dData.frontTires;
      return this.tires = this.rearTires.concat(this.frontTires);
    };

    return Car;

  })();

}).call(this);
